title: Plain talk
author: Amrithnath <arjun.amrith@gmail.com>
email: hello@hello
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Well im just here evaluating jekyll and gh pages. Hey stalker, nice stalking!JK!

# social links
twitter_username: arjunamrith # DO NOT include the @ character, or else the build will fail!
github_username:  arjunamrith # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
